apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
  namespace: mywebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: mycontainer1
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "redhat"
        - name: MYSQL_DATABASE
          value: "Pranjal"
---
apiVersion: v1
kind: Service
metadata:
    name: db-svc
    namespace: mywebsite
spec:
    ports:
     - port: 3306
       protocol: TCP
       targetPort: 3306
    selector:
       app: mywebsite