apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywb
  namespace: mywebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywb
  template:
    metadata:
      labels:
        app: mywb
    spec:
      containers:
      - name: mycontainer2
        image: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "10.107.50.167"
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_PASSWORD
          value: "redhat"
        - name: WORDPRESS_DB_NAME
          value: "Pranjal"